export const publicSanityDocumentTypes = [
  "siteSettings",
  "homePage",
  "navigation",
  "page",
  "service",
  "job",
  "insight",
  "caseStudy",
  "salarySnapshot",
  "testimonial",
  "faq",
  "person",
  "ctaBlock",
  "proofItem",
  "redirect",
] as const;

export const privateOperationalStores = [
  "Railway Postgres",
  "private object storage for future CV files",
  "private object storage for future David's Take audio notes",
] as const;

export const forbiddenSanityFieldNames = [
  "candidateName",
  "candidateEmail",
  "candidatePhone",
  "candidateLinkedInUrl",
  "candidateProfileUrl",
  "candidateStatus",
  "candidateProfile",
  "cv",
  "cvFile",
  "cvUrl",
  "cvFileUrl",
  "coverLetter",
  "applicationRecord",
  "applicationStatus",
  "clientContactEmail",
  "privateClientContact",
  "privateNotes",
  "internalStatus",
  "leadHistory",
  "clientShortlist",
  "shortlistFeedback",
  "audioNote",
  "audioNoteUrl",
  "audioTranscript",
  "davidsAudioNote",
  "davidsTakeAudio",
  "clientPortalToken",
  "magicLinkToken",
  "candidatePresentation",
  "candidateRanking",
  "candidateScore",
  "aiCandidateScore",
  "aiCandidateRanking",
  "aiRejectionReason",
  "aiPrompt",
  "aiTranscript",
  "aiCandidateSummary",
  "aiClientProfileDraft",
  "aiInterviewTranscript",
  "aiDraftOutput",
  "aiSuitabilityScore",
  "interviewRequest",
  "consentRecord",
  "dsarRequest",
  "auditLog",
] as const;

export function isForbiddenSanityFieldName(fieldName: string) {
  return forbiddenSanityFieldNames.includes(
    fieldName as (typeof forbiddenSanityFieldNames)[number],
  );
}
