version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "08:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    labels:
      - dependency-management
      - ci-quality
    commit-message:
      prefix: deps
      include: scope
    groups:
      npm-production-security:
        applies-to: security-updates
        dependency-type: production
        patterns:
          - "*"
      npm-development-security:
        applies-to: security-updates
        dependency-type: development
        patterns:
          - "*"
      npm-production-minor-and-patch:
        applies-to: version-updates
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      npm-development-minor-and-patch:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "08:30"
      timezone: Europe/London
    open-pull-requests-limit: 3
    labels:
      - dependency-management
      - ci-quality
    commit-message:
      prefix: deps
      include: scope
    groups:
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
      github-actions-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
