import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import {
  buildRecruiterLabsCalendarDraft,
  futureGoogleCalendarEnvVars,
  getRecruiterLabsInterviewSchedulingReadiness,
  recruiterLabsInterviewSchedulingEnvVars,
  recruiterLabsInterviewSchedulingFeatureFlags,
} from "@/lib/recruiter-labs-interview-scheduling";

vi.mock("server-only", () => ({}));

describe("Recruiter Labs interview scheduling orchestration", () => {
  it("keeps interview scheduling feature flags explicit and off by default", () => {
    expect(recruiterLabsInterviewSchedulingFeatureFlags).toEqual([
      "FEATURE_INTERVIEW_REQUEST_WORKFLOW",
      "FEATURE_WHATSAPP_INTERVIEW_SCHEDULING",
      "FEATURE_GOOGLE_MEET_INTERVIEW_SCHEDULING",
    ]);
    expect(recruiterLabsInterviewSchedulingEnvVars).toContain(
      "WHATSAPP_BUSINESS_INTERVIEW_AVAILABILITY_TEMPLATE",
    );
    expect(futureGoogleCalendarEnvVars).toContain(
      "GOOGLE_CALENDAR_REFRESH_TOKEN",
    );

    expect(getRecruiterLabsInterviewSchedulingReadiness({})).toMatchObject({
      manualFirst: true,
      interviewWorkflowEnabled: false,
      googleMeetFeatureEnabled: false,
      googleOAuthConfigured: false,
      readyForManualScheduling: false,
      readyForWhatsAppLogistics: false,
      readyForGoogleCalendarAutomation: false,
      safeForAutomaticCalendarEvents: false,
    });
  });

  it("allows manual scheduling readiness without approving Google automation", () => {
    const readiness = getRecruiterLabsInterviewSchedulingReadiness({
      FEATURE_INTERVIEW_REQUEST_WORKFLOW: "true",
      FEATURE_WHATSAPP_INTERVIEW_SCHEDULING: "true",
      FEATURE_GOOGLE_MEET_INTERVIEW_SCHEDULING: "true",
      OPERATIONS_DB_ENABLED: "true",
      DATABASE_URL: "postgres://example",
      WHATSAPP_BUSINESS_ENABLED: "true",
      WHATSAPP_BUSINESS_PHONE_NUMBER_ID: "123",
      WHATSAPP_BUSINESS_ACCESS_TOKEN: "token",
      GOOGLE_CALENDAR_CLIENT_ID: "client",
      GOOGLE_CALENDAR_CLIENT_SECRET: "secret",
      GOOGLE_CALENDAR_REFRESH_TOKEN: "refresh",
      GOOGLE_CALENDAR_ID: "calendar",
    });

    expect(readiness.readyForManualScheduling).toBe(true);
    expect(readiness.readyForWhatsAppLogistics).toBe(true);
    expect(readiness.googleOAuthConfigured).toBe(true);
    expect(readiness.readyForGoogleCalendarAutomation).toBe(false);
    expect(readiness.safeForAutomaticCalendarEvents).toBe(false);
    expect(readiness.blockers).toContain(
      "Automatic Google Calendar event creation is not implemented.",
    );
  });

  it("blocks calendar drafts until David approves contact and the final slot", () => {
    expect(
      buildRecruiterLabsCalendarDraft({
        roleTitle: "Marketing Director",
        candidateLabel: "Candidate Name",
        clientLabel: "Client Name",
        scheduledStartAt: "2026-06-12T10:00:00.000Z",
        scheduledEndAt: "2026-06-12T11:00:00.000Z",
        candidateContactApproved: false,
        davidApprovedFinalSlot: true,
      }),
    ).toMatchObject({
      ok: false,
      code: "candidate_contact_not_approved",
      manualOnly: true,
    });

    expect(
      buildRecruiterLabsCalendarDraft({
        roleTitle: "Marketing Director",
        candidateLabel: "Candidate Name",
        clientLabel: "Client Name",
        scheduledStartAt: "2026-06-12T10:00:00.000Z",
        scheduledEndAt: "2026-06-12T11:00:00.000Z",
        candidateContactApproved: true,
        davidApprovedFinalSlot: false,
      }),
    ).toMatchObject({
      ok: false,
      code: "david_approval_required",
      manualOnly: true,
    });
  });

  it("builds a manual Google Calendar draft without creating an event", () => {
    const draft = buildRecruiterLabsCalendarDraft({
      roleTitle: "Marketing Director",
      candidateLabel: "Candidate Name",
      clientLabel: "Client Name",
      scheduledStartAt: "2026-06-12T10:00:00.000Z",
      scheduledEndAt: "2026-06-12T11:00:00.000Z",
      timezone: "Europe/London",
      locationType: "google_meet",
      candidateContactApproved: true,
      davidApprovedFinalSlot: true,
    });

    expect(draft).toMatchObject({
      ok: true,
      code: "draft_ready",
      manualOnly: true,
      title: "Interview: Marketing Director",
      location: "Google Meet link to be generated by David in Google Calendar",
      scheduledStartAt: "2026-06-12T10:00:00.000Z",
      scheduledEndAt: "2026-06-12T11:00:00.000Z",
      timezone: "Europe/London",
    });
    expect(draft.description).toContain("David to approve");
    expect(draft.description).toContain(
      "Keep sensitive notes, CV detail and salary negotiation out of the calendar body.",
    );
    expect(draft.warnings).toContain(
      "Google Calendar and Meet automation is not created by this helper.",
    );
  });

  it("stages the private database model without message bodies or secrets", () => {
    const migration = readFileSync(
      "database/migrations/028_recruiter_labs_interview_scheduling_orchestration.sql",
      "utf8",
    );

    for (const table of [
      "recruiter_lab_interview_availability",
      "recruiter_lab_interview_events",
      "recruiter_lab_interview_messages",
      "recruiter_lab_interview_scheduling_tasks",
    ]) {
      expect(migration).toContain(table);
    }

    expect(migration).toContain("token_hash");
    expect(migration).toContain("google_calendar_event_id");
    expect(migration).toContain("google_meet_url");
    expect(migration).toContain("recipient_hash");
    expect(migration).toContain("error_summary");
    expect(migration).not.toMatch(/message_body|raw_message|message_text/i);
    expect(migration).not.toMatch(/access_token|client_secret|refresh_token/i);
  });

  it("documents the staged scheduling architecture and blockers", () => {
    const doc = readFileSync(
      "docs/recruiter-labs-interview-scheduling.md",
      "utf8",
    );
    const readme = readFileSync("README.md", "utf8");
    const launchGate = readFileSync(
      "docs/recruiter-labs-client-pipeline-launch-gate.md",
      "utf8",
    );

    expect(doc).toContain("# Recruiter Labs Interview Scheduling");
    expect(doc).toContain("## Staged Scheduling Architecture");
    expect(doc).toContain("## WhatsApp Flow");
    expect(doc).toContain("## Google Calendar And Meet Flow");
    expect(doc).toContain("## Approval Gates");
    expect(doc).toContain("## Database Model");
    expect(doc).toContain("## Environment Variables");
    expect(doc).toContain("## Security And Privacy Safeguards");
    expect(doc).toContain("manual-first");
    expect(doc).toContain("No spam");
    expect(doc).toContain("No secrets leaked");
    expect(doc).not.toMatch(/Google Calendar event creation is live/i);
    expect(readme).toContain("docs/recruiter-labs-interview-scheduling.md");
    expect(launchGate).toContain("manual-first calendar draft orchestration");
  });
});
